name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  go_router: ^16.3.0
  camera: ^0.11.3
  web_socket_channel: ^3.0.3
  google_mlkit_selfie_segmentation: ^0.10.0 
  google_mlkit_face_detection: ^0.13.1
  image: ^4.5.4
  sensors_plus: ^7.0.0
  audioplayers: ^6.5.1
  flutter_tts: ^4.2.3
  intl: ^0.20.2
  google_fonts: ^6.3.2
  youtube_player_flutter: ^9.1.3
  socket_io_client: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/overlays/
    - assets/sounds/
